# Generated by Django 2.2.24 on 2021-10-27 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20211027_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimeinto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
