# Generated by Django 2.2.24 on 2021-10-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20211027_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimeinto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
