# Generated by Django 2.2.24 on 2021-10-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0005_auto_20211028_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimeinto',
            field=models.DateField(null=True),
        ),
    ]
