# Generated by Django 2.2.24 on 2021-11-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0006_auto_20211028_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_nacimeinto',
            new_name='fecha_nacimiento',
        ),
    ]
