# Generated by Django 2.2.24 on 2021-10-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoriales', '0003_auto_20211027_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('paginas', models.IntegerField()),
                ('publicado', models.BooleanField()),
                ('fecha_publicacion', models.DateField()),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='editoriales.Editorial')),
            ],
        ),
    ]
