# Generated by Django 2.2.24 on 2021-10-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20211027_0045'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', to='autores.Autor'),
        ),
    ]
