# Generated by Django 2.2.24 on 2021-10-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20211027_0045'),
        ('libros', '0002_libro_autores'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditoresLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autores.Autor')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='editores',
            field=models.ManyToManyField(through='libros.EditoresLibro', to='autores.Autor'),
        ),
    ]
