# Generated by Django 2.2.24 on 2021-11-10 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0003_auto_20211027_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lilbros_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
