# Generated by Django 2.2.24 on 2021-10-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
