# Generated by Django 2.2.24 on 2021-10-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0002_editorial_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
