# Generated by Django 2.2.24 on 2021-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0003_auto_20211027_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
